### ISSUE TITLE
fix: Failed to create team

### ISSUE THREAD

**Issue by colinmollenhour** [HugoRCD/shelve#523]
### Environment

Docker compose project adapted from the docs, deployed on Coolify.
- 
- App container: ghcr.io/hugorcd/shelve:latest (as of March 28)

### Version

v2.0.0.beta-20 (I think? Assuming the latest container is the latest releast)

### Reproduction

New install, login with Github, try to create a team.

### Description

I deployed a fresh instance of Shelve on Coolify and was able to authenticate with my GitHub app, but on the onboard page I get a "Failed to create team" error toast.

- There are no errors in the container logs
- I set `NUXT_PRIVATE_ADMIN_EMAILS` to my github user email address

My one user exists in the database and the email matches the  `NUXT_PRIVATE_ADMIN_EMAILS` value.
```
shelve=# select * from users;
 id |    username     |        email         |                      avatar                       | role | authType | onboarding | cliInstalled |        updatedAt        |         createdAt          
----+-----------------+----------------------+---------------------------------------------------+------+----------+------------+--------------+-------------------------+----------------------------
  1 | colinmollenhour | c*****.com | https://avatars.githubusercontent.com/u/38738?v=4 | user | github   | f          | f            | 2025-03-28 16:07:30.493 | 2025-03-28 16:07:30.506105
(1 row)
```

Any ideas?

### Logs

```shell-script

```

**Comment by HugoRCD** [comment]
@colinmollenhour Ok so first of all it's very strange because if you set your emails to admin you should be admin in the db and then what did you use as a team name? And do you get stuck on onboarding? Or does it change if you refresh/delete your cookies?

**Comment by colinmollenhour** [comment]
I used "ShipStream" and also tried "shipstream". I can only go to onboarding and the home page. The home page redirects me to `/onboarding`. I cleared all cookies for the domain through developer tools Application tab and refreshed the page. Same.

**Comment by colinmollenhour** [comment]
I never got the email due to the from address of the email not being authenticated on my Resend account, I think it's your domain. Is there a link in the email that I must visit first?

**Comment by HugoRCD** [comment]
Ok I'll try to reproduce this locally but I've just done it with the `latest` and for the moment I can't manage to make the mistake again! But I'll keep you posted!

**Comment by HugoRCD** [comment]
Yes it's normal if you don't put your Resend token it won't send the mail but it's useless other than to say welcome!

**Comment by colinmollenhour** [comment]
But the sender is hard-coded to your address: https://github.com/HugoRCD/shelve/blob/d497ef3fcf0944d0daa2756cc5b4013e3a9ee75a/apps/shelve/server/services/resend.ts#L9
So Resend refuses to send (this I did see in the container logs)

**Comment by HugoRCD** [comment]
That's something I'm going to sort out as soon as possible indeed!

**Comment by colinmollenhour** [comment]
No worries, looks like a great app, you crank out good stuff!

I set up Hashicorp Vault once but its overkill so thought I'd try Shelve. No rush from me, just kicking the tires.

**Comment by HugoRCD** [comment]
Thank you very much, I try to do my best to make it as simple, pleasant and pretty as possible! But yeah, it's quite complicated to keep everything perfect with the work at Nuxtlabs on the side! But don't hesitate to make issues, I'll be happy to solve them!

**Comment by HugoRCD** [comment]
@colinmollenhour Ok I'm too stupid, CORS middleware is maybe a bit abused 😅 Do you also have this error?

![Image](https://github.com/user-attachments/assets/0f360d86-7949-4698-b7eb-85065f73bb0b)

**Comment by HugoRCD** [comment]
relate #532

**Comment by HugoRCD** [comment]
Ok I just tested with the new version you can pull the `latest` image and personally with a fresh install it works!

**Comment by HugoRCD** [comment]
@colinmollenhour I close the issue for now since I think the problem has been fixed if you still encounter the error, you can open another one!

**Comment by colinmollenhour** [comment]
I'm still getting the same error with the latest version (using the :latest docker tag from ghcr.io)..

I suggest adding `console.error(error)` anywhere that you hide the error message from the user so it's easier to report issues.

For example, here between line 68 and 69: https://github.com/HugoRCD/shelve/commit/88be7547e10709aa6f7ab685c5519ab1dec20449#diff-58150dea594c178c13099308e98f7065ca09a448acde32fbe3760878914acf57R66-R69

**Comment by HugoRCD** [comment]
@colinmollenhour Well that's super weird because I really can't reproduce the error even with fresh installs, I'm doing a PR that will definitely improve the connection with Github I'll take the opportunity to add some logs then too!
In the meantime, can you send me the error you're seeing in the console, at network level?

**Comment by colinmollenhour** [comment]
I wiped the database, cleared cookies, then authenticated again (Github) and this time I got the welcome email. But I still get the same error when trying to onboard.

**Comment by HugoRCD** [comment]
@colinmollenhour Yes I put the ability to custom email sender but can you send me the network window with the error? I'm going to push the new flow for the github app and additional console logs by tonight!

**Comment by colinmollenhour** [comment]
I just pulled it and redeployed the container and I still get the same error.. Here are the container logs:

```
2025-04-09T01:10:47.021450716Z Running database migrations...
2025-04-09T01:10:47.965198173Z 
2025-04-09T01:10:47.965228204Z > @shelve/app@ db:push /app
2025-04-09T01:10:47.965232264Z > drizzle-kit push
2025-04-09T01:10:47.965235144Z 
2025-04-09T01:10:48.258375891Z No config path provided, using default 'drizzle.config.ts'
2025-04-09T01:10:48.258771330Z Reading config file '/app/drizzle.config.ts'
2025-04-09T01:10:49.516043959Z Using 'pg' driver for database querying
2025-04-09T01:10:49.937292258Z Error: Cannot find module '../../../../packages/types'
2025-04-09T01:10:49.937349828Z Require stack:
2025-04-09T01:10:49.937353578Z - /app/server/database/schema.ts
2025-04-09T01:10:49.937356518Z - /app/node_modules/.pnpm/drizzle-kit@0.30.6/node_modules/drizzle-kit/bin.cjs
2025-04-09T01:10:49.937359358Z     at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
2025-04-09T01:10:49.937361938Z     at Function._load (node:internal/modules/cjs/loader:1055:27)
2025-04-09T01:10:49.937364458Z     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-09T01:10:49.937366978Z     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
2025-04-09T01:10:49.937369548Z     at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-09T01:10:49.937372038Z     at require (node:internal/modules/helpers:136:16)
2025-04-09T01:10:49.937374918Z     at Object.<anonymous> (/app/server/database/schema.ts:4:42)
2025-04-09T01:10:49.937377908Z     at Module._compile (node:internal/modules/cjs/loader:1554:14)
2025-04-09T01:10:49.937380548Z     at Module._compile (/app/node_modules/.pnpm/drizzle-kit@0.30.6/node_modules/drizzle-kit/bin.cjs:14147:30)
2025-04-09T01:10:49.937383198Z     at node:internal/modules/cjs/loader:1706:10 {
2025-04-09T01:10:49.937385708Z   code: 'MODULE_NOT_FOUND',
2025-04-09T01:10:49.937388168Z   requireStack: [
2025-04-09T01:10:49.937390628Z     '/app/server/database/schema.ts',
2025-04-09T01:10:49.937393148Z     '/app/node_modules/.pnpm/drizzle-kit@0.30.6/node_modules/drizzle-kit/bin.cjs'
2025-04-09T01:10:49.937395698Z   ]
2025-04-09T01:10:49.937398278Z }
2025-04-09T01:10:49.985950645Z Starting the Shelve application...
2025-04-09T01:10:51.742136637Z Listening on http://[::]:3000
```

And browser:

![Image](https://github.com/user-attachments/assets/fe62608d-6a69-4218-be08-66fc45bf4be3)

**Comment by colinmollenhour** [comment]
Ahh, I looked back over your comment and #532 and see that I was missing `NUXT_PRIVATE_ALLOWED_ORIGINS` in my env. I set that and it's working great now!

Thanks for your help!

I tweaked your Coolify template a bit, and I think it works really well now:

```
services:
  app:
    image: 'ghcr.io/hugorcd/shelve:latest'
    restart: always
    environment:
      - SERVICE_FQDN_APP=/
      - 'DATABASE_URL=postgres://shelve:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/shelve'
      - 'NUXT_PRIVATE_REDIS_URL=${NUXT_PRIVATE_REDIS_URL:-redis://redis:6379}'
      - 'NUXT_PRIVATE_ENCRYPTION_KEY=${SERVICE_PASSWORD_SHELVE}'
      - 'NUXT_SESSION_PASSWORD=${SERVICE_PASSWORD_SHELVE}'
      - 'NUXT_OAUTH_GITHUB_CLIENT_ID=${NUXT_OAUTH_GITHUB_CLIENT_ID}'
      - 'NUXT_OAUTH_GITHUB_CLIENT_SECRET=${NUXT_OAUTH_GITHUB_CLIENT_SECRET}'
      - 'NUXT_OAUTH_GOOGLE_CLIENT_ID=${NUXT_OAUTH_GOOGLE_CLIENT_ID}'
      - 'NUXT_OAUTH_GOOGLE_CLIENT_SECRET=${NUXT_OAUTH_GOOGLE_CLIENT_SECRET}'
      - 'NUXT_PRIVATE_RESEND_API_KEY=${NUXT_PRIVATE_RESEND_API_KEY}'
      - 'NUXT_PRIVATE_SENDER_EMAIL=${NUXT_PRIVATE_SENDER_EMAIL}'
      - 'NUXT_PRIVATE_ADMIN_EMAILS=${NUXT_PRIVATE_ADMIN_EMAILS}'
      - 'NUXT_PRIVATE_ALLOWED_ORIGINS=${SERVICE_FQDN_APP}'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000/api/hello'
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
  postgres:
    image: 'postgres:17-alpine'
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: shelve
      POSTGRES_PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
      POSTGRES_DB: shelve
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - shelve
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: 'redis:7.4-alpine'
    restart: always
    volumes:
      - 'redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres: null
  redis: null
```
